### ISSUE TITLE
Hashnode Link

### ISSUE THREAD

**Issue by Spyder15** [WeMakeDevs/events#4]
We Can Add Link Of Hashnode , where if some user come to repo he/she directly click on link for more detail

**Comment by AzimWarsii** [comment]
Yeah It would be a great idea to add links to previous winner's hashnode blogs

**Comment by siddhant-khisty** [comment]
@AzimWarsii Great idea. Will implement this soon.

@Spyder15 I'm not sure I get what you mean.

**Comment by Malavi1** [comment]
The beginners like me know something about the topic but we are failing drastically in the representation!! Do add winners blogs link it will help alot
